version: '3.4'

services:
    eshopdb:
        container_name: eshopdb
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=EShopDb
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_eshopdb:/var/lib/postgresql/data/

    distributedcache:
        container_name: distributedcache
        restart: always
        ports:
            - "6379:6379"

    seq:
        container_name: seq
        environment:
            - ACCEPT_EULA=Y
        restart: always
        ports:
            - "5341:80"
            - "5342:5341"
    
    messagebus:
         container_name: messagebus
         hostname: ecommerce-mq
         restart: always
         ports:
            - "5672:5672"    # AMQP protocol
            - "15672:15672"  # Management UI
         environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

    identity:
         container_name: identity
         environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB=postgres
            - KC_DB_URL=jdbc:postgresql://eshopdb/EShopDb?currentSchema=identity
            - KC_DB_USERNAME=postgres
            - KC_DB_PASSWORD=postgres
         restart: always
         ports:
            - "9090:8080"
         command:
            - start-dev
